- name: expense project 
  hosts: local
  connection: local
  vars:
    nexus:
    - mysql
    - backend
    - frontend
    zone: rupakalpan.shop
  tasks:
  - name: install boto
    ansible.builtin.pip:
      name:
      - boto3
      - botocore
      executable: pip3.9
  - name: create ec2 instances
    amazon.aws.ec2_instance:
      name: "{{ item }} "
      vpc_subnet_id: "subnet-00a686d0e79dedb31"
      instance_type: "t3.micro"
      security_group: "sg-0201d0d466a3135e4"
      image_id: ami-09c813fb71547fc4f
      wait: true
    loop: "{{ nexus }}"
    register: reso
  - name: display name
    ansible.builtin.debug:
      msg: "{{ reso }}"
  - name: create rout53 records
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ item.item }}.{{ zone }}"
      type: A
      ttl: 1
      value: "{{item.instances[0].private_ip_address}}"
      wait: true
      overwrite: true
    loop: "{{reso.results}}"    
  - name: create rout53 records
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ zone }}"
      type: A
      ttl: 1
      value: "{{item.instances[0].public_ip_address}}"
      wait: true
      overwrite: true
    loop: "{{reso.results}}"
    when: item.item == "frontend"